const defaultTheme = {
  colors: {
    base:'#767676',
    baseWhite :'#FFF',
    primary:'#111',
    secondary:'#767676',
    danger:'#EB00#B',
    dangerText:'#ED50136',
    dangerBorder:'#FCD4DE',
    dangerBg:'#FEECF0',
    warning:'#FFB724',
    warningText:'#9869A',
    warningBorder:'#FFFAC1',
    warningBg:'#FFF8E9',
    success:'#008A1E',
    successText:'#006E18',
    successBorder:'#CEE9D4',
    successBg:'#EEF7F0',
    information:'#2768FF',
    informationText:'#1F53CC',
    informationBorder:'#D4E1FF',
    informationBg:'#E9F0FF',
  },
  fonts : {
    headingLarge:'5rem',
    headingMedium:'4rem',
    headingSmall:'3.2rem',
    titleLarge:'2.6rem',
    bodyLarge:'2rem',
    bodyMedium:'1.6rem',
    bodySmall:'1.4rem',
    weightBold :'700',
  },
  shape :{
    small:'6x',
    medium:'8px',
    large:'10px',
  },
  spacing : {
    spacing1:'1.2rem',
    spacing2:'1.6rem',
    spacing3:'2rem',
    spacing4:'2.4rem',
    spacing5:'3.2rem',
    spacing6:'4rem',
    spacing7:'6.4rem',
    spacing8:'8rem',
  }
};

export default defaultTheme;